#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["peoplecontext-client @ git+https://github.com/pocketcontext/peoplecontext.git@a6d507d5e67a005afe8ff425bec0cf90e8943b32"]
# ///
from peoplecontext_client.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
